#!/usr/bin/env python3
"""Generate every agent-specific copy of the style from one canonical file.

The canonical file is output-styles/attention-control.md. Claude Code reads it
directly as an output style. Every other agent needs the same rules in its own
container: a skill, a rules file, or an agent-instruction file. Those copies are
real files rather than symlinks, so Windows clones and GitHub ZIP downloads work.

    python3 scripts/sync_style.py            # write the copies
    python3 scripts/sync_style.py --check    # exit 1 when a copy has drifted
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "output-styles" / "attention-control.md"

GENERATED_BY = (
    "<!-- Generated by scripts/sync_style.py from output-styles/attention-control.md."
    " Do not edit this file. -->"
)

SKILL_FRONTMATTER = """---
name: attention-control
description: 'Shape output for a reader with ADHD, then write each sentence in controlled English: action first, one word one meaning, active voice, simple tenses, state restated every turn. Invoke with /attention-control; stays on until "stop attention control".'
disable-model-invocation: true
license: MIT
metadata:
  hermes:
    tags: [ADHD, Output Style, Accessibility, Simplified Technical English]
    category: productivity
    related_skills: []
---
"""

SKILL_INVOCATION = """## Invocation

These rules stay on for the rest of the session. Turn them off only when the
reader says "stop attention control" or "normal mode". Confirm in one line, then
return to your default style.
"""

AGENTS_PREAMBLE = """# Attention Control

Shape every response for a reader with ADHD, then write each sentence in
controlled English. The full ruleset follows. It applies to every response in
this repository.
"""

CURSOR_FRONTMATTER = """---
description: 'Action-first output in controlled English, shaped for an ADHD reader.'
alwaysApply: true
---
"""


def split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter, body). Frontmatter is empty when the file has none."""
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---\n", 3)
    if end == -1:
        raise ValueError(f"{CANONICAL}: unterminated YAML frontmatter")
    return text[: end + 5], text[end + 5 :].lstrip("\n")


def build_skill(body: str) -> str:
    return f"{SKILL_FRONTMATTER}\n{GENERATED_BY}\n\n{body.rstrip()}\n\n{SKILL_INVOCATION}"


def build_cursor_rule(body: str) -> str:
    return f"{CURSOR_FRONTMATTER}\n{GENERATED_BY}\n\n{body.rstrip()}\n"


def build_agents(body: str) -> str:
    heading, _, rest = body.partition("\n")
    if not heading.startswith("# "):
        rest = body
    return f"{AGENTS_PREAMBLE}\n{GENERATED_BY}\n\n{rest.strip()}\n"


TARGETS = {
    Path("skills/attention-control/SKILL.md"): build_skill,
    Path(".cursor/skills/attention-control/SKILL.md"): build_skill,
    Path(".cursor/rules/attention-control.mdc"): build_cursor_rule,
    Path("AGENTS.md"): build_agents,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report drift and exit 1 instead of writing the copies",
    )
    args = parser.parse_args(argv)

    _, body = split_frontmatter(CANONICAL.read_text(encoding="utf-8"))
    drifted: list[Path] = []

    for relative, builder in TARGETS.items():
        target = ROOT / relative
        expected = builder(body)
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == expected:
            continue
        if args.check:
            drifted.append(relative)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected, encoding="utf-8")
        print(f"wrote {relative}")

    if drifted:
        for relative in drifted:
            print(f"ERROR: {relative} does not match the canonical style", file=sys.stderr)
        print("Run: python3 scripts/sync_style.py", file=sys.stderr)
        return 1

    if args.check:
        print(f"All {len(TARGETS)} copies match {CANONICAL.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
